small_talk = [
    [r'(.*) weather (.*)',
     ["What do you think about the weather today?",
      "Do you enjoy the weather today?"]],
    [r'I like (.*)',
     ["Why do you like {0}?",
      "That's great, what else do you like?"]],
    [r'I dislike (.*)',
     ["Why don't you like {0}?",
      "What do you like instead?"]],
    [r'(.*) raining (.*)',
     ["Do you like rain or do you prefer sunny weather?",
      "How does the rain affect you?"]],
    [r'(.*) sunny (.*)',
     ["Do you enjoy sunny weather?",
      "What do you like to do on sunny days?"]]]